site_name: 3DGS based SLAM | Material Collection
repo_url: https://github.com/jinghan-turtle/3DGS-Collection
repo_name: 3DGS-Collection
copyright: Copyright &copy; 2025 jinghan-turtle with all rights reserved


theme:
  name: material
  custom_dir: overrides
  logo: assets/3D-Gaussians.png
  favicon: assets/3D-Gaussians.png

  font:
    text: Noto Serif SC
  language: zh

  features:
    - announce.dismiss       # 呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.tracking    # 地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs        # 顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    - navigation.sections    # 启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top         # 返回顶部的按钮 在上滑时出现
    - navigation.footer      # 页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest         # 搜索输入一些字母时推荐补全整个单词
    - search.highlight       # 搜索出的文章关键词加入高亮
    - search.share           # 搜索分享按钮
    - navigation.expand      # 打开Tab时左侧目录全部展开
    - navigation.indexes     # 启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: jinghan-color-light
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: jinghan-color-light
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  plugins:
    - tags
    - search

  # icon:
  #   repo: fontawesome/brands/github


nav:
  - Background: index.md
  - 3DGS: 
    - 3D Gaussian Splatting: 3DGS/3DGS.md
  - Decode:
    - Overview: decode/Overview.md
    - Details:
      - Class Encapsulation: decode/Details/Class_Encapsulation.md
      - Can Data Analysis: decode/Details/Can_Data_Analysis.md


# 详见https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
# https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
markdown_extensions: 
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format  # 代码块高亮插件
  - pymdownx.arithmatex:    # latex支持
      generic: true
  - tables
  - toc:
      permalink: true       # 固定标题位置为当前位置
  - pymdownx.highlight:     # 代码块高亮
      anchor_linenums: true
      linenums: false       # 显示行号
      # auto_title: true    # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  generator: false
  homepage: https://jinghan-turtle.github.io/3DGS-Collection/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jinghan-turtle
      name: Github
    - icon: fontawesome/solid/paper-plane
      link: mailto:<caijinghan@sjtu.edu.cn>
      name: Email me
  analytics:
    provider: google
    property: G-NSSC5W311R
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
