site_name: 3DGS based SLAM | Material Collection
repo_url: https://github.com/jinghan-turtle/3DGS-Collection
repo_name: 3DGS-Collection
copyright: Copyright &copy; 2025 jinghan-turtle with all rights reserved


theme:
  language: zh
  name: material
  custom_dir: overrides
  logo: assets/3D-Gaussians.png
  favicon: assets/3D-Gaussians.png

  features:
    - announce.dismiss
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - content.tooltips
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - toc.follow
    - toc.integrate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: Morandi-light


nav:
  - Background: index.md
  - 3DGS: 
    - 3D Gaussian Splatting: 3DGS/3DGS.md
  - Decode:
    - Overview: decode/Overview.md
    - Details:
      - Class Encapsulation: decode/Details/Class_Encapsulation.md
      - Can Data Analysis: decode/Details/Can_Data_Analysis.md


markdown_extensions: 
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format  # 代码块高亮插件
      preserve_tabs: true
  - pymdownx.arithmatex:    # latex支持
      generic: true
  - tables
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      toc_depth: 3
  - pymdownx.highlight:     # 代码块高亮
      anchor_linenums: true
      linenums: false       # 显示行号
      # auto_title: true    # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true


extra:
  generator: false
  homepage: https://jinghan-turtle.github.io/3DGS-Collection/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jinghan-turtle/3DGS-Collection
      name: Github
    - icon: fontawesome/solid/paper-plane
      link: mailto:<caijinghan@sjtu.edu.cn>
      name: Email me
  analytics:
    provider: google
    property: G-NSSC5W311R
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!


extra_css:
  - stylesheets/extra.css
  - https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap
  - https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@450&display=swap


extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
